# Set base image (host OS)
FROM python:3.8

# Set the working directory in the Docker image filesystem.
WORKDIR /app/frontend

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . .

# Command to run on container start
CMD ["streamlit", "run", "main.py"]
