name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Access OPENAI_API_KEY from secrets
          USERNAME_SECRET: ${{ env.USERNAME_SECRET }}  # Access USERNAME_SECRET from secrets
          PASSWORD_SECRET: ${{ env.PASSWORD_SECRET }}  # Access PASSWORD_SECRET from secrets
          AUTH_ALGORITHM: ${{ env.AUTH_ALGORITHM }}  # Access AUTH_ALGORITHM from secrets
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ env.ACCESS_TOKEN_EXPIRE_MINUTES }}  # Access ACCESS_TOKEN_EXPIRE_MINUTES from secrets
          SECRET_KEY: ${{ secrets.SECRET_KEY }}  # Access SECRET_KEY from secrets
        run: pytest