name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Access OPENAI_API_KEY from secrets
        run: pytest

  merge:
    name: Merge with main
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}  # Ensuring that all the tests are passing before merging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge with main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git merge --ff-only ${{ github.head_ref }}
          git push